#!/usr/bin/env python3
"""
Скрипт для помощи в получении cookies Facebook для facebook-scraper

Использование:
1. Запустите этот скрипт
2. Следуйте инструкциям для получения cookies из браузера
3. Скрипт создаст файл cookies.txt в формате Netscape
"""

import os
import sys

def print_instructions():
    """Выводит инструкции по получению cookies"""
    print("=" * 70)
    print("ИНСТРУКЦИЯ ПО ПОЛУЧЕНИЮ COOKIES ДЛЯ FACEBOOK SCRAPER")
    print("=" * 70)
    print()
    print("Способ 1: Через Developer Tools (Рекомендуется)")
    print("-" * 70)
    print("1. Откройте браузер и войдите в Facebook (https://www.facebook.com)")
    print("2. Нажмите F12 (или Cmd+Option+I на Mac) для открытия Developer Tools")
    print("3. Перейдите на вкладку 'Application' (Chrome) или 'Storage' (Firefox)")
    print("4. В левой панели найдите 'Cookies' → 'https://www.facebook.com'")
    print("5. Найдите следующие cookies и скопируйте их значения:")
    print("   - c_user (ваш User ID)")
    print("   - xs (токен сессии)")
    print("   - datr (опционально, но рекомендуется)")
    print()
    print("6. Введите значения ниже:")
    print()
    
    c_user = input("Введите значение cookie 'c_user': ").strip()
    xs = input("Введите значение cookie 'xs': ").strip()
    datr = input("Введите значение cookie 'datr' (опционально, Enter для пропуска): ").strip()
    
    if not c_user or not xs:
        print("\n❌ Ошибка: c_user и xs обязательны!")
        return None
    
    # Формат Netscape для facebook-scraper
    cookies_lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by get_facebook_cookies.py",
        "",
        f".facebook.com\tTRUE\t/\tFALSE\t0\tc_user\t{c_user}",
        f".facebook.com\tTRUE\t/\tFALSE\t0\txs\t{xs}",
    ]
    
    if datr:
        cookies_lines.append(f".facebook.com\tTRUE\t/\tFALSE\t0\tdatr\t{datr}")
    
    cookies_content = "\n".join(cookies_lines)
    
    # Сохраняем в файл
    cookies_file = "cookies.txt"
    with open(cookies_file, "w") as f:
        f.write(cookies_content)
    
    print(f"\n✅ Cookies сохранены в файл: {cookies_file}")
    print("\nТеперь вы можете использовать этот файл:")
    print("  client = FacebookScraperClient(cookies='cookies.txt')")
    print()
    
    return cookies_file


def print_alternative_method():
    """Альтернативный способ через Network tab"""
    print("\n" + "=" * 70)
    print("АЛЬТЕРНАТИВНЫЙ СПОСОБ: Через Network Tab")
    print("=" * 70)
    print()
    print("1. Откройте Facebook в браузере и войдите")
    print("2. Откройте Developer Tools (F12)")
    print("3. Перейдите на вкладку 'Network'")
    print("4. Обновите страницу (F5)")
    print("5. Найдите любой запрос к facebook.com")
    print("6. Откройте запрос → вкладка 'Headers'")
    print("7. Найдите 'Cookie:' в Request Headers")
    print("8. Скопируйте всю строку Cookie")
    print()
    print("Вставьте строку Cookie ниже (или нажмите Enter для пропуска):")
    cookie_string = input("Cookie: ").strip()
    
    if not cookie_string:
        return None
    
    # Парсим cookie строку
    cookies_dict = {}
    for item in cookie_string.split("; "):
        if "=" in item:
            key, value = item.split("=", 1)
            cookies_dict[key.strip()] = value.strip()
    
    if "c_user" not in cookies_dict or "xs" not in cookies_dict:
        print("\n❌ Ошибка: Не найдены обязательные cookies (c_user, xs)")
        return None
    
    # Конвертируем в формат Netscape
    cookies_lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by get_facebook_cookies.py",
        "",
    ]
    
    for key, value in cookies_dict.items():
        cookies_lines.append(f".facebook.com\tTRUE\t/\tFALSE\t0\t{key}\t{value}")
    
    cookies_content = "\n".join(cookies_lines)
    
    cookies_file = "cookies.txt"
    with open(cookies_file, "w") as f:
        f.write(cookies_content)
    
    print(f"\n✅ Cookies сохранены в файл: {cookies_file}")
    return cookies_file


def main():
    print("\n" + "=" * 70)
    print("FACEBOOK COOKIES HELPER")
    print("=" * 70)
    print()
    print("Выберите способ получения cookies:")
    print("1. Через Application/Storage tab (рекомендуется)")
    print("2. Через Network tab (альтернативный)")
    print("3. Выход")
    print()
    
    choice = input("Ваш выбор (1-3): ").strip()
    
    if choice == "1":
        cookies_file = print_instructions()
    elif choice == "2":
        cookies_file = print_alternative_method()
    elif choice == "3":
        print("Выход...")
        sys.exit(0)
    else:
        print("❌ Неверный выбор!")
        sys.exit(1)
    
    if cookies_file:
        print("\n" + "=" * 70)
        print("СЛЕДУЮЩИЕ ШАГИ:")
        print("=" * 70)
        print()
        print("1. Файл cookies.txt создан в текущей директории")
        print("2. Теперь обновите main.py, чтобы использовать cookies:")
        print()
        print("   client = FacebookScraperClient(cookies='cookies.txt')")
        print()
        print("3. Или установите переменную окружения:")
        print("   export FACEBOOK_COOKIES_FILE=cookies.txt")
        print()
        print("⚠️  ВАЖНО:")
        print("   - Не делитесь файлом cookies.txt ни с кем!")
        print("   - Добавьте cookies.txt в .gitignore")
        print("   - Cookies могут истечь, обновляйте их при необходимости")
        print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nПрервано пользователем")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Ошибка: {e}")
        sys.exit(1)

